name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # Versões fixadas para consistência
  PYTHON_VERSION: '3.12'
  BLACK_VERSION: '24.8.0'
  ISORT_VERSION: '5.13.2'
  FLAKE8_VERSION: '7.1.1'

jobs:
  # Job de Linting e Formatação
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-lint-${{ env.BLACK_VERSION }}-${{ env.ISORT_VERSION }}-${{ env.FLAKE8_VERSION }}
          restore-keys: |
            ${{ runner.os }}-pip-lint-

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "black==${{ env.BLACK_VERSION }}" "isort==${{ env.ISORT_VERSION }}" "flake8==${{ env.FLAKE8_VERSION }}"

      - name: Run Black
        run: black --check --diff app/ tests/ main.py

      - name: Run isort
        run: isort --profile black --check-only --diff app/ tests/ main.py

      - name: Run flake8
        run: flake8 app/ tests/ main.py

  # Job de Testes Unitários
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ curl

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov coverage pytest-xvfb psutil

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=app --cov-report=xml --cov-report=term-missing -v

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Job de Testes com Docker
  docker-test:
    name: Docker Tests
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for testing
        uses: docker/build-push-action@v5
        with:
          context: .
          target: development
          load: true
          tags: autou-classifier:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -e PROVIDER=OpenAI \
            -e LOG_LEVEL=ERROR \
            autou-classifier:test \
            python -m pytest --cov=app --cov-report=term-missing -v

  # Job de Docker Compose Test
  docker-compose-test:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from template
        run: |
          cp .env.example .env
          # Set test-specific environment variables
          echo "OPENAI_API_KEY=test-key-placeholder" >> .env
          echo "APP_ENV=testing" >> .env
          echo "DEBUG=false" >> .env
          echo "LOG_LEVEL=ERROR" >> .env
          echo "PROVIDER=OpenAI" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build services with docker-compose
        run: |
          # Build all services
          docker compose build --parallel
          
      - name: Start services with docker-compose
        run: |
          # Start services in background
          docker compose up -d app
          
      - name: Wait for services to be ready
        run: |
          # Wait for app service to be healthy
          echo "Waiting for app service to be ready..."
          timeout 120s bash -c 'until curl -f http://localhost:8000/health > /dev/null 2>&1; do sleep 2; done'
          echo "✅ App service is ready"
          
      - name: Run health checks
        run: |
          # Test health endpoint
          curl -f http://localhost:8000/health
          echo "✅ Health check passed"
          
      - name: Run tests with docker-compose
        run: |
          # Run tests using the test profile
          docker compose --profile test run --rm test
          
      - name: Run linting with docker-compose
        run: |
          # Run linting using the lint profile
          docker compose --profile lint run --rm lint
          
      - name: Show service logs on failure
        if: failure()
        run: |
          echo "=== App Service Logs ==="
          docker compose logs app
          echo "=== Test Service Logs ==="
          docker compose logs test || true
          echo "=== Lint Service Logs ==="
          docker compose logs lint || true
          
      - name: Cleanup
        if: always()
        run: |
          docker compose down -v --remove-orphans

  # Job de Build e Deploy
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [test, docker-test, docker-compose-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=commit-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Job de Testes de Performance
  performance-test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install psutil

      - name: Run performance tests
        run: |
          python -m pytest tests/test_performance.py -v --tb=short

  # Job de Segurança
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  # Job de Release (opcional)
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-and-deploy, performance-test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[release]')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        run: |
          echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0)..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## Changes
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ## Docker Image
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ```
          draft: false
          prerelease: false
